module:
  addtocal: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  bg_image_formatter: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  bootstrap_site_alert: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_a11ychecker: 0
  ckeditor_accordion: 0
  ckeditor_balloonpanel: 0
  ckeditor_bootstrap_buttons: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editoria11y: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  responsive_background_image: 0
  responsive_bg_image_formatter: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simplesamlphp_auth: 0
  social_media_links: 0
  social_media_links_field: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  time_field: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  ds: 1
  ds_extras: 2
  externalauth: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  radix: 0
  penn_starter: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
